repos:
- repo: https://github.com/doublify/pre-commit-isort
  rev: v4.3.0
  hooks:
    - id: isort
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-yaml
      exclude: '.*/templates/.*\.yaml'
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: name-tests-test
    - id: requirements-txt-fixer
    - id: sort-simple-yaml
    - id: trailing-whitespace
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.86.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_tflint
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.23
  hooks:
    - id: helmlint
