extends: default

ignore:
  - .terraform
  - '**/Chart.lock'
  - '**/templates/**.yaml'

rules:
  comments:
    require-starting-space: true
    min-spaces-from-content: 1
  comments-indentation:
    level: error
  document-start: false
  empty-lines:
    max: 1
  empty-values: enable
  line-length: disable
  truthy:
    check-keys: false
