#!/bin/bash
set -e

terraform -chdir=./infra init
terraform -chdir=./infra apply

aws eks update-kubeconfig --name k8s-platform

helm repo add argo https://argoproj.github.io/argo-helm
helm install argocd argo/argo-cd --namespace argocd --create-namespace
helm upgrade argocd ./bootstrap/argo/ --namespace argocd --create-namespace -f ./bootstrap/argo/values.yaml
