#!/bin/bash
set -e

terraform -chdir=./infra init
terraform -chdir=./infra apply

aws eks update-kubeconfig --name k8s-platform

helm install argocd ./bootstrap/argo/ \
  --namespace argocd \
  -f ./bootstrap/argo/values.yaml \
  --dependency-update \
  --create-namespace
