#!/bin/bash
set -e

terraform -chdir=./infra init
terraform -chdir=./infra apply

helm repo add argo https://argoproj.github.io/argo-helm
helm install argocd argo/argo-cd \
  --namespace argocd \
  --create-namespace \
  --dependency-update
helm upgrade argocd ./bootstrap/argo/ \
  --namespace argocd \
  -f ./bootstrap/argo/values-prod.yaml
