apiVersion: v2
name: prometheus
description: deploying prometheus community chart
type: application
version: 0.0.1
dependencies:
  - name: kube-prometheus-stack
    version: 15.1.3
    repository: "https://prometheus-community.github.io/helm-charts"
