apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .Values.default.name }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
spec:
  template:
    spec:
      nodeClassRef:
        name: {{ .Values.default.name }}
      requirements:
        {{- .Values.default.requirements | toYaml | nindent 8 }}
  limits:
    cpu: {{ .Values.default.limits.cpu }}
    memory: {{ .Values.default.limits.memory }}
  disruption:
    consolidationPolicy: {{ .Values.default.disruption.consolidationPolicy }}
    consolidateAfter: {{ .Values.default.disruption.consolidateAfter }}
    budgets:
      {{- .Values.default.disruption.budgets | toYaml | nindent 4 }}
