{{- range $key, $store := .Values.clusterSecretStore }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ $store.name }}
  labels:
      {{- include "external-secrets.labels" $ | nindent 6 }}
      {{- with $store.additionalLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
spec:
  provider:
    {{ toYaml $store.provider | nindent 6 }}
{{- end }}
