apiVersion: apps/v1
kind: Deployment
metadata:
  name: details
  namespace: {{ .Values.namespace }}
  labels:
    app: details
    version: v1
spec:
  replicas: {{ .Values.details.deployment.replicaCount }}
  selector:
    matchLabels:
      app: details
      version: v1
  template:
    metadata:
      labels:
        app: details
        version: v1
    spec:
      serviceAccountName: {{ .Values.details.serviceAccount.name }}
      containers:
      - name: details
        image: "{{ .Values.details.deployment.container.repo }}:{{ .Values.details.deployment.container.tag }}"
        imagePullPolicy: {{ .Values.details.deployment.container.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.details.deployment.container.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-v1
  namespace: {{ .Values.namespace }}
  labels:
    app: ratings
    version: v1
spec:
  replicas: {{ .Values.ratings.deployment.replicaCount }}
  selector:
    matchLabels:
      app: ratings
      version: v1
  template:
    metadata:
      labels:
        app: ratings
        version: v1
    spec:
      serviceAccountName: {{ .Values.ratings.serviceAccount.name }}
      containers:
      - name: ratings
        image: "{{ .Values.ratings.deployment.container.repo }}:{{ .Values.ratings.deployment.container.tag }}"
        imagePullPolicy: {{ .Values.ratings.deployment.container.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.ratings.deployment.container.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v1
  namespace: {{ .Values.namespace }}
  labels:
    app: reviews
    version: v1
spec:
  replicas: {{ .Values.reviews.deployment.replicaCount }}
  selector:
    matchLabels:
      app: reviews
      version: v1
  template:
    metadata:
      labels:
        app: reviews
        version: v1
    spec:
      serviceAccountName: {{ .Values.reviews.serviceAccount.name }}
      containers:
      - name: reviews
        image: "{{ .Values.reviews.deployment.v1.container.repo }}:{{ .Values.reviews.deployment.v1.container.tag }}"
        imagePullPolicy: {{ .Values.reviews.deployment.v1.container.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.reviews.deployment.v1.container.port }}
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
      volumes:
      - name: tmp
        emptyDir: {}
      - name: wlp-output
        embtyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v2
  namespace: {{ .Values.namespace }}
  labels:
    app: reviews
    version: v2
spec:
  replicas: {{ .Values.reviews.deployment.replicaCount }}
  selector:
    matchLabels:
      app: reviews
      version: v2
  template:
    metadata:
      labels:
        app: reviews
        version: v2
    spec:
      serviceAccountName: {{ .Values.reviews.serviceAccount.name }}
      containers:
      - name: reviews
        image: "{{ .Values.reviews.deployment.v2.container.repo }}:{{ .Values.reviews.deployment.v2.container.tag }}"
        imagePullPolicy: {{ .Values.reviews.deployment.v2.container.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.reviews.deployment.v2.container.port }}
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
      volumes:
      - name: tmp
        emptyDir: {}
      - name: wlp-output
        embtyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v3
  namespace: {{ .Values.namespace }}
  labels:
    app: reviews
    version: v3
spec:
  replicas: {{ .Values.reviews.deployment.replicaCount }}
  selector:
    matchLabels:
      app: reviews
      version: v3
  template:
    metadata:
      labels:
        app: reviews
        version: v3
    spec:
      serviceAccountName: {{ .Values.reviews.serviceAccount.name }}
      containers:
      - name: reviews
        image: "{{ .Values.reviews.deployment.v3.container.repo }}:{{ .Values.reviews.deployment.v3.container.tag }}"
        imagePullPolicy: {{ .Values.reviews.deployment.v3.container.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.reviews.deployment.v3.container.port }}
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
      volumes:
      - name: tmp
        emptyDir: {}
      - name: wlp-output
        embtyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage
  namespace: {{ .Values.namespace }}
  labels:
    app: productpage
    version: v1
spec:
  replicas: {{ .Values.productpage.deployment.replicaCount }}
  selector:
    matchLabels:
      app: productpage
      version: v1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
    spec:
      serviceAccountName: {{ .Values.productpage.serviceAccount.name }}
      containers:
      - name: productpage
        image: "{{ .Values.productpage.deployment.container.repo }}:{{ .Values.productpage.deployment.container.tag }}"
        imagePullPolicy: {{ .Values.productpage.deployment.container.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.productpage.deployment.container.port }}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
