apiVersion: v1
kind: Service
metadata:
  name: details
  namespace: {{ .Values.namespace }}
  labels:
    app: details
    service: details
spec:
  ports:
    - port: {{ .Values.details.service.port }}
      name: http
  selector:
    app: details
