apiVersion: v1
kind: Service
metadata:
  name: details
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.details.labels | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.details.service.ports.port }}
      name: {{ .Values.details.service.ports.name }}
  selector:
    {{- toYaml .Values.details.selector | nindent 4}}
---
apiVersion: v1
kind: Service
metadata:
  name: ratings
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.ratings.labels | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.ratings.service.ports.port }}
      name: {{ .Values.ratings.service.ports.name }}
  selector:
    {{- toYaml .Values.ratings.service.selector | nindent 4}}
---
apiVersion: v1
kind: Service
metadata:
  name: reviews
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.reviews.labels | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.reviews.service.ports.port }}
      name: {{ .Values.reviews.service.ports.name }}
  selector:
    {{- toYaml .Values.reviews.service.selector | nindent 4}}
---
apiVersion: v1
kind: Service
metadata:
  name: productpage
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.productpage.labels | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.productpage.service.ports.port }}
      name: {{ .Values.productpage.service.ports.name }}
  selector:
    {{- toYaml .Values.productpage.service.selector | nindent 4}}
