apiVersion: v2
name: karpenter
description: A Helm chart for Karpenter
type: application
version: 1.0.0
appVersion: 0.37.0

dependencies:
  - name: karpenter
    version: "0.37.0"
    repository: oci://public.ecr.aws/karpenter
