kube-prometheus-stack:
  # -- the prometheus operator configuration
  prometheus:
    ## -- Settings affecting prometheusSpec
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#prometheusspec
    prometheusSpec:
      # -- how long to retain metrics
      retention: 1h

      # -- default true, restricts Prometheus to only discover and scrape ServiceMonitors that match the release labels set by helm (itself in this case)
      # setting to false allows the operators to add serviceMonitors defined externally
      serviceMonitorSelectorNilUsesHelmValues: false

      ## -- number of replicas of each shard to deploy for a Prometheus deployment
      ## number of replicas multiplied by shards is the total number of Pods created
      replicas: 1
