name: ci

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.tf"
  push:
    branches:
      - main
    paths:
      - "**.tf"

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    concurrency: terraform
    defaults:
      run:
        working-directory: platform/terraform
    env:
      TF_IN_AUTOMATION: "true"
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: fmt
        id: fmt
        run: terraform fmt -check

      - name: init
        id: init
        run: terraform init -upgrade -input=false

      - name: validate
        id: validate
        run: terraform validate -no-color

      - name: tflint setup
        uses: terraform-linters/setup-tflint@v4
        id: tflint-setup
        with:
          tflint_version: "latest"
          tflint_wrapper: "true"

      - name: tflint init
        id: tflint-init
        run: tflint --init

      - name: tflint check
        id: tflint-check
        run: tflint --var-file=tfvars/prod.tfvars
