name: ci
run-name: ${{ github.base_ref }} ci

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'

permissions:
  contents: read

jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init
        run: terraform init

      - name: Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate
